title: Hello, world! We're Team D
description: This is a page
permalink: ':title/'
baseurl: ''
url: ''
author: Team D
author-img: david-freeman.jpg
about-author: I am a web developer focusing on front-end development. Always hungry to keep learning.
twitter: null
facebook: null
github: null
linkedin: null
email: null
discus-identifier: mr-brown
analytics: null
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
paginate: 8
paginate_path: '/page/:num'
exclude:
  - node_modules
  - gulpfile.js
  - package.json
  - yarn.lock
