# Setup
title:        teamD dev blog
tagline:      A development blog for learning and testing
baseurl:      "/teamD-devblog"
paginate:     1

# About/contact
author:       
  name:       teamD
  url:        https://solid-graphics.github.io/teamD-devblog/ 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown