# Setup
title:        teamD Dev Blog
tagline:      A Development Blog for Miguel Silveira and Rui D'Orey
baseurl:      "/teamD-devblog" 
paginate:     1

# About/contact
author:       
  name:       teamD
  url:        https://solid-graphics.github.io/teamD-devblog/ 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown